version: 0.2

# phases:
#   pre_build:
#     commands:
#       - npm install
#   build:
#     commands:
#       - npm run build

# artifacts:
#   files:
#     - '**/*'
#   discard-paths: no
#   base-directory: build



phases:
  install:
    runtime-versions:
      nodejs: 18 # Or whatever Node version you're using
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: .next   # Specify your build folder!
  discard-paths: no
