import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { isMobile } from "react-device-detect";
import "./globals.css";
import ThemeProvider from "@/provider/themeProvider";
import JotaiProvider from "@/provider/jotaiProvider";
import Header from "@/components/layout/mobile/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JotaiProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {!isMobile ? <Header /> : <></>}
            {children}
          </ThemeProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
